spring:
  application:
    name: opera-service
  datasource:
    url: jdbc:postgresql://localhost:5432/opera_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: public

# Server configuration
server:
  port: 8081
  servlet:
    context-path: /api

# Logging configuration
logging:
  level:
    org.springframework: INFO
    com.opera.operaservice: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# GraphQL Federation
federation:
  enabled: true
  service:
    name: opera-service
    version: 1.0.0
    url: http://localhost:8081/graphql

# Shows Service URL for Feign client
shows:
  service:
    url: http://localhost:8082

# API Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

# Liquibase configuration
liquibase:
  change-log: classpath:db/changelog/db.changelog-master.xml
  enabled: true
  default-schema: public
  user: postgres
  password: postgres
  url: jdbc:postgresql://localhost:5432/opera_db
  driver-class-name: org.postgresql.Driver
  change-log-parameters:
    app.schema: public
